apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      initContainers:
        - name: init-discovery-server
          image: busybox
          command: ['sh', '-c', 'until nc -z discovery-server 8761; do echo waiting for discovery-server; sleep 2; done;']
      containers:
        - name: admin-server
          image: {{ .Values.IMAGE_TAG_ADMIN_SERVER }}
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "512Mi"
      imagePullSecrets:
        - name: gcp-artifact-registry