apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
   - name: http
     port: 8080
     targetPort: 8080
     nodePort: 30001
     protocol: TCP