apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  type: NodePort
  ports:
   - name: http
     port: 8888
     targetPort: 8888
     nodePort: 30000
     protocol: TCP
