apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  type: NodePort
  ports:
   - name: http
     port: 8081
     targetPort: 8081
     nodePort: 30002
     protocol: TCP
