apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: NodePort
  ports:
   - name: http
     port: 8761
     targetPort: 8761
     nodePort: 30005
     protocol: TCP
