apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      initContainers:
        - name: init-config-server
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 2; done;']
      containers:
        - name: discovery-server
          image: {{ .Values.IMAGE_TAG_DISCOVERY_SERVER }}
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10         
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      imagePullSecrets:
        - name: gcp-artifact-registry