apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - name: grafana-server
          image: {{ .Values.IMAGE_TAG_GRAFANA_SERVICE }}
          ports:
            - containerPort: 3030
          resources:
            limits:
              memory: "256Mi"
      imagePullSecrets:
        - name: gcp-artifact-registry