apiVersion: v1
kind: Service
metadata:
  name: grafana-server
spec:
  selector:
    app: grafana-server
  type: NodePort
  ports:
   - name: http
     port: 3030
     targetPort: 3030
     nodePort: 30008
     protocol: TCP
