apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
   - name: http
     port: 9091
     targetPort: 9090
     nodePort: 30009
     protocol: TCP