apiVersion: v1
kind: Service
metadata:
  name: tracing-server
spec:
  selector:
    app: tracing-server
  type: NodePort
  ports:
   - name: http
     port: 9411
     targetPort: 9411
     nodePort: 30006
     protocol: TCP


