apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  type: NodePort
  ports:
   - name: http
     port: 8083
     targetPort: 8083
     nodePort: 30004
     protocol: TCP
