apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  selector:
    app: visits-service
  type: NodePort
  ports:
   - name: http
     port: 8082
     targetPort: 8082
     nodePort: 30003
     protocol: TCP
