apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      initContainers:
        - name: init-discovery-server
          image: busybox
          command: ['sh', '-c', 'until nc -z discovery-server 8761; do echo waiting for discovery-server; sleep 2; done;']
      containers:
        - name: visits-service
          image: {{ .Values.IMAGE_TAG_VISITS_SERVICE }}
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "512Mi"
      imagePullSecrets:
        - name: gcp-artifact-registry